verbose = true
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false
single_line_if_else = true
reorder_imports = true
take_source_hints = false
max_width = 120
ideal_width = 100
fn_call_width = 80
struct_lit_width = 80
fn_arg_indent = "Tabbed"
where_pred_indent = "Tabbed"
generics_indent = "Tabbed"
chain_base_indent = "Tabbed"
chain_indent = "Tabbed"
