[package]
name = "evalbot"
version = "0.1.0"
authors = ["angelsl <hidingfromhidden@gmail.com>"]

[dependencies]
irc = ">= 0.9.1"
toml = ">= 0.1.23"
rustc-serialize = ">= 0.3.16"
byteorder = ">= 0.4.2"
clippy = ">= 0.0.24"
