verbose = true
fn_brace_style = "PreferSameLine"
item_brace_style = "PreferSameLine"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false
single_line_if_else = true
