[package]
name = "evalbotlib"
version = "0.2.0"
authors = ["angelsl <hidingfromhidden@gmail.com>"]

[features]
unixsocket = []

[dependencies]
toml = ">= 0.0.0"
serde = ">= 0.0.0"
serde_derive = ">= 0.0.0"
byteorder = ">= 0.0.0"
crossbeam = ">= 0.0.0"
